name: Reusable job
on:
  workflow_call:


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v3
      with:
       name  : my-artifact

    - name: Display structure of downloaded files
      run: |
        ls -R
        cat the-file.txt
